import type { Metadata } from "next";
import "./globals.css";
import QueryProvider from "@/provider/providers";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "Saas Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children,}: Readonly<{ children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body >
        <QueryProvider>
        {children}
            <ToastContainer/>
        </QueryProvider>
      </body>
    </html>
  );
}
