import React from "react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

interface UserData {
  _id: string;
  name: string;
  email: string;
  revenue: number;
}

interface PdfGeneratorProps {
  data: UserData[];
}

const PdfGenerator: React.FC<PdfGeneratorProps> = ({ data }) => {
  const generatePDF = () => {
    if (!data || data.length === 0) {
      alert("No data available to generate PDF!");
      return;
    }

    const doc = new jsPDF();

    // ===== Header =====
    doc.setFontSize(18);
    doc.text("total users Revenue Report", 14, 18);

    doc.setFontSize(11);
    const currentDate = new Date().toLocaleString();
    doc.text(`Generated on: ${currentDate}`, 14, 25);

    // ===== Table =====
    const tableColumn = ["S.No", "Name", "Email", "Revenue"];
    const tableRows = data.map((user, index) => [
      user._id.slice(0,10)+`...`,
      user.name,
      user.email,
      user.revenue,
    ]);

    autoTable(doc, {
      head: [tableColumn],
      body: tableRows,
      startY: 35,
      styles: { fontSize: 10 },
      headStyles: { fillColor: [66, 133, 244] },
    });

    // ===== Summary =====
    const totalRevenue = data.reduce((sum, user) => sum + user.revenue, 0);
    const finalY = (doc as any).lastAutoTable.finalY || 35;
    doc.text(`Total Revenue: ${totalRevenue}  ₹`, 14, finalY + 10);

    // ===== Footer =====
    doc.setFontSize(10);
    doc.text("Generated by Harshit’s React App", 14, doc.internal.pageSize.height - 10);

    // ===== Save PDF =====
    doc.save("revenue_report.pdf");
  };

  return (
    <div className="p-2 text-right" data-testid="pdfGenerator">
      <button
        onClick={generatePDF}
        className="bg-blue-600 text-white px-3 py-1 rounded mt-4 hover:bg-blue-700"
      >
        Download PDF
      </button>
    </div>
  );
};

export default PdfGenerator;
